spring:
  profiles.active: local
---
spring:
  profiles: default
server:
   port:9000
rabbitmq:
  email-queue: notification.queue.email
  routingkey : notification.queue.email
  exchange : ELMS.TES.DIR.EXG
mail:
  serviceEnabled: true
  protocol: smtp
  auth: false
---
spring:
  profiles: local
server:
   port:9000
rabbitmq:
  host: localhost
  virtualhost: localhost
  username: guest
  password: guest
mail:
  host: mailhub.lss.emc.com
---
spring:
  profiles: cloud
rabbitmq:
  service-name: TeS_Rmq
mail:
  host: mailhub.lss.emc.com