spring:
  profiles.active: local
---
spring:
  profiles: default
server:
   port:9000
mail:
  serviceEnabled: true
  protocol: smtp
  auth: false
---
spring:
  profiles: local
server:
   port:9000
mail:
  host: mailhub.aaa.bbb.com
---
spring:
  profiles: cloud
mail:
  host: mailhub.aaa.bbb.com